scrivi_database:-
tell('casi/prove.pl'),
    listing(ass(_,_,_,_)),
    listing(atomica/1),
    listing(att/2),
    listing(atomica_ind/2),
    listing(significativa/3),
    listing(fonte_sign/2),
    listing(base_stratificata/1),
    listing(cl_l/2),
    listing(asserisce_clausole/2),
    listing(modelli/2),
    listing(bpac/2),
    listing(b/2),
    listing(b_ns/2),
    listing(good/3),
    listing(g_s/2),
    listing(d_s/3),
    listing(media/3),
    listing(credibile/2),
    listing(nuova_att/2),
    listing(ordinatoBO/3),
    told.

    %salva nel database tutti i predicati dinamici